import{a as L,i as h,S as g}from"./assets/vendor-6e0bf343.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function y(o,t){const s={key:"43249690-fb8fa8f624055727458ab84aa",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t},a="https://pixabay.com/api/";return(await L.get(a,{params:s})).data}function w({largeImageURL:o,webformatURL:t,tags:s,likes:a,views:e,comments:r,downloads:n}){return`<li class="gallery-item">
          <a href="${o}"> <img loading="lazy" src="${t}" alt="${s}" width="360" height="152"/> </a>
          <div class="gallery-item-description">
            <p class="description"><b>Likes</b> ${a}</p>
            <p class="description"><b>Views</b> ${e}</p>
            <p class="description"><b>Comments</b> ${r}</p>
            <p class="description"><b>Downloads</b> ${n}</p>
            </div>
          </li>`}function b(o){return o.map(w).join("")}function S(){return document.querySelector(".gallery-item").getBoundingClientRect().height}const c=document.querySelector(".search-form"),d=document.querySelector(".gallery"),f=document.querySelector(".loader"),l=document.querySelector(".loader-more"),m=document.querySelector(".btn-more");let u="",i=1,p=0;const M=15;c.addEventListener("submit",q);m.addEventListener("click",x);async function q(o){o.preventDefault(),f.classList.remove("visually-hidden"),u=c.elements.searchInput.value,i=1,d.innerHTML="";const t=await y(u,i);try{t.hits.length<1&&h.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",position:"topRight"});const s=b(t.hits);d.insertAdjacentHTML("beforeend",s);const a=new g(".gallery a",{captionsData:"alt",captionDelay:250});c.reset(),f.classList.add("visually-hidden"),a.refresh()}catch(s){console.log(s)}p=Math.ceil(t.totalHits/M),v()}function P(){m.classList.remove("visually-hidden")}function $(){m.classList.add("visually-hidden")}function v(){i>=p?$():P()}async function x(){i+=1,l.classList.remove("visually-hidden");const o=await y(u,i);try{i>=p&&(l.classList.add("visually-hidden"),h.show({title:"Error",message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#ef4040",position:"topRight"}));const t=b(o.hits);d.insertAdjacentHTML("beforeend",t);const s=new g(".gallery a",{captionsData:"alt",captionDelay:250});c.reset(),l.classList.add("visually-hidden"),s.refresh()}catch(t){console.log(t)}window.scrollBy({top:S()*2,left:0,behavior:"smooth"}),v()}
//# sourceMappingURL=commonHelpers.js.map
