import{a as L,i as h,S as y}from"./assets/vendor-6e0bf343.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();async function g(s,t){const o={key:"43249690-fb8fa8f624055727458ab84aa",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t},a="https://pixabay.com/api/";return(await L.get(a,{params:o})).data}function w({largeImageURL:s,webformatURL:t,tags:o,likes:a,views:e,comments:r,downloads:n}){return`<li class="gallery-item">
          <a href="${s}"> <img loading="lazy" src="${t}" alt="${o}" width="360" height="152"/> </a>
          <div class="gallery-item-description">
            <p class="description"><b>Likes</b> ${a}</p>
            <p class="description"><b>Views</b> ${e}</p>
            <p class="description"><b>Comments</b> ${r}</p>
            <p class="description"><b>Downloads</b> ${n}</p>
            </div>
          </li>`}function b(s){return s.map(w).join("")}const c=document.querySelector(".search-form"),d=document.querySelector(".gallery"),m=document.querySelector(".loader"),l=document.querySelector(".loader-more"),p=document.querySelector(".btn-more");let u="",i=1,f=0;const M=15;c.addEventListener("submit",S);p.addEventListener("click",$);async function S(s){s.preventDefault(),m.classList.remove("visually-hidden"),u=c.elements.searchInput.value,i=1,d.innerHTML="";const t=await g(u,i);try{t.hits.length<1&&h.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",position:"topRight"});const o=b(t.hits);d.insertAdjacentHTML("beforeend",o);const a=new y(".gallery a",{captionsData:"alt",captionDelay:250});c.reset(),m.classList.add("visually-hidden"),a.refresh()}catch(o){console.log(o)}f=Math.ceil(t.totalHits/M),v()}function P(){p.classList.remove("visually-hidden")}function q(){p.classList.add("visually-hidden")}function v(){i>=f?q():P()}async function $(){i+=1,l.classList.remove("visually-hidden");const s=await g(u,i);try{i>=f&&(l.classList.add("visually-hidden"),h.show({title:"Error",message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#ef4040",position:"topRight"}));const t=b(s.hits);d.insertAdjacentHTML("beforeend",t);const o=new y(".gallery a",{captionsData:"alt",captionDelay:250});c.reset(),l.classList.add("visually-hidden"),o.refresh()}catch(t){console.log(t)}window.scrollBy({top:getParam()*2,left:0,behavior:"smooth"}),v()}
//# sourceMappingURL=commonHelpers.js.map
