import{i as l,S as u}from"./assets/vendor-8c59ed88.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();function d(o){const s="https://pixabay.com",r="/api/",i=new URLSearchParams({key:"43249690-fb8fa8f624055727458ab84aa",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}),e=`${s}${r}?${i}`;return fetch(e).then(t=>t.json())}function p({largeImageURL:o,webformatURL:s,tags:r,likes:i,views:e,comments:t,downloads:n}){return`<li class="gallery-item">
          <a href="${o}"> <img src="${s}" alt="${r}" width="360" height="152"/> </a>
          <div class="gallery-item-description">
            <p class="description"><b>Likes</b> ${i}</p>
            <p class="description"><b>Views</b> ${e}</p>
            <p class="description"><b>Comments</b> ${t}</p>
            <p class="description"><b>Downloads</b> ${n}</p>
            </div>
          </li>`}function f(o){return o.map(p).join("")}const c=document.querySelector(".search-form"),m=document.querySelector(".gallery"),a=document.querySelector(".loader");c.addEventListener("submit",h);function h(o){o.preventDefault(),a.classList.remove("visually-hidden");const s=c.elements.searchInput.value;d(s).then(r=>{r.hits.length<1&&(l.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",position:"topRight"}),a.classList.add("visually-hidden"));const i=f(r.hits);m.innerHTML=i;const e=new u(".gallery a",{captionsData:"alt",captionDelay:250});c.reset(),a.classList.add("visually-hidden"),e.refresh()}).catch(r=>console.log(r))}
//# sourceMappingURL=commonHelpers.js.map
